import { GoogleGenerativeAI } from "npm:@google/generative-ai";

export interface OrchestratorContext {
  topic: string;
  weakTopics: Array<{ topic: string }>;
  recentQuizResults: Array<{ score: number }>;
  teacherText: string;
  interactionsCount: number;
}

/**
 * The Orchestrator Subagent ONLY outputs JSON. It reads the final text generated by the 
 * Teacher subagent, looks at the student's metrics, and decides if a tool should be launched.
 *
 * It is completely isolated from the conversational prompt, preventing JSON formatting errors.
 */
export async function getOrchestratorAction(
  apiKey: string,
  context: OrchestratorContext
): Promise<string | null> {
  // If the conversation is brand new, don't overwhelm with tools yet
  if (context.interactionsCount < 2) return null;

  const genAI = new GoogleGenerativeAI(apiKey);
  // Enforce JSON mode for perfect reliability
  const model = genAI.getGenerativeModel({
    model: "gemini-flash-latest",
    // Gemini 1.5 feature: strictly enforce JSON schema output
    generationConfig: {
      responseMimeType: "application/json",
      temperature: 0.1,
    }
  });

  const orchestratorPrompt = `
You are the Orchestrator for an AI tutor application. Your ONLY job is to output a single JSON object (or empty object) based on the current conversation state. Do not output any markdown formatting, only pure JSON.

STUDENT STATE:
Topic: ${context.topic}
Total messages in this session: ${context.interactionsCount}
Weak Topics: ${context.weakTopics.map(w => w.topic).join(', ')}

TEACHER'S LATEST RESPONSE:
"${context.teacherText.slice(-500)}"

DECISION RULES:
1. **Action Triggers**:
   - ONLY trigger "trigger_flashcards" or "trigger_quiz" if the user EXPLICITLY asks (e.g., "quiz me", "give me flashcards").
   - Trigger "trigger_visualizer" if the user explicitly asks for a diagram/map OR if explaining a complex system where a visual aid is clearly beneficial.
   - Do NOT trigger tools based on general academic progress or as a way to "pulse" learner knowledge unless requested.
2. In ALL OTHER CASES, output an empty JSON object: {}

REQUIRED JSON SCHEMA:
If triggering a tool, output exactly this and nothing else:
{"action": "trigger_quiz", "topic": "[Specific Topic Name]"}

Valid actions: "trigger_quiz", "trigger_flashcards", "trigger_visualizer".
`;

  try {
    const result = await model.generateContent(orchestratorPrompt);
    const jsonString = result.response.text().trim();

    // Check if the model decided to do nothing
    if (!jsonString || jsonString === "{}" || jsonString === '{\n}') {
      return null;
    }

    // Try to quickly validate the JSON structure
    JSON.parse(jsonString);
    return jsonString;
  } catch (error) {
    console.warn("Orchestrator Subagent opted out or failed JSON shape:", error);
    return null;
  }
}
